// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _profile_card from './profile-card.bones.json'

registerBones({
  "profile-card": _profile_card,
})
